
package com.txu.webserviceclients.soap.wsdlimports;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UtilityPlanServiceImpl", targetNamespace = "http://soap.services.registrationapp.txu.com/", wsdlLocation = "http://localhost:8080/TXUCustomerRegistrationServices/soapservices/serviceplans?wsdl")
public class UtilityPlanServiceImpl
    extends Service
{

    private final static URL UTILITYPLANSERVICEIMPL_WSDL_LOCATION;
    private final static WebServiceException UTILITYPLANSERVICEIMPL_EXCEPTION;
    private final static QName UTILITYPLANSERVICEIMPL_QNAME = new QName("http://soap.services.registrationapp.txu.com/", "UtilityPlanServiceImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/TXUCustomerRegistrationServices/soapservices/serviceplans?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UTILITYPLANSERVICEIMPL_WSDL_LOCATION = url;
        UTILITYPLANSERVICEIMPL_EXCEPTION = e;
    }

    public UtilityPlanServiceImpl() {
        super(__getWsdlLocation(), UTILITYPLANSERVICEIMPL_QNAME);
    }

    public UtilityPlanServiceImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), UTILITYPLANSERVICEIMPL_QNAME, features);
    }

    public UtilityPlanServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, UTILITYPLANSERVICEIMPL_QNAME);
    }

    public UtilityPlanServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UTILITYPLANSERVICEIMPL_QNAME, features);
    }

    public UtilityPlanServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UtilityPlanServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UtilityPlanService
     */
    @WebEndpoint(name = "UtilityPlanServiceImplPort")
    public UtilityPlanService getUtilityPlanServiceImplPort() {
        return super.getPort(new QName("http://soap.services.registrationapp.txu.com/", "UtilityPlanServiceImplPort"), UtilityPlanService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UtilityPlanService
     */
    @WebEndpoint(name = "UtilityPlanServiceImplPort")
    public UtilityPlanService getUtilityPlanServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.services.registrationapp.txu.com/", "UtilityPlanServiceImplPort"), UtilityPlanService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UTILITYPLANSERVICEIMPL_EXCEPTION!= null) {
            throw UTILITYPLANSERVICEIMPL_EXCEPTION;
        }
        return UTILITYPLANSERVICEIMPL_WSDL_LOCATION;
    }

}
