
package com.txu.webserviceclients.soap.wsdlimports;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UtilityPlanService", targetNamespace = "http://soap.services.registrationapp.txu.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UtilityPlanService {


    /**
     * 
     * @return
     *     returns java.util.List<com.txu.webserviceclients.soap.wsdlimports.ServicePlan>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServicePlans", targetNamespace = "http://soap.services.registrationapp.txu.com/", className = "com.txu.webserviceclients.soap.wsdlimports.GetServicePlans")
    @ResponseWrapper(localName = "getServicePlansResponse", targetNamespace = "http://soap.services.registrationapp.txu.com/", className = "com.txu.webserviceclients.soap.wsdlimports.GetServicePlansResponse")
    public List<ServicePlan> getServicePlans();

}
